---
# tasks file for mapr_maprlogin

- name: obtain a MapR ticket for a user
  sudo_user: "{{maprlogin_admin_username}}"
  shell: echo {{maprlogin_pw_clear}} | maprlogin password -user {{maprlogin_username}} 
  no_log: true
